apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cno-system
commonLabels:
  cno/resource: "true"
secretGenerator:
- name: cno-config
  envs:
  - env.secret
  type: Opaque
configMapGenerator:
- name: cno-config
  envs:
  - env.config
resources:
- namespace.yaml
- keycloak
- kafka

replacements:
- path: keycloak/replacements-related-image-keycloak-init.yaml
- path: keycloak/replacements-related-image-keycloak.yaml
- path: keycloak/replacements-related-image-postgresql.yaml
- path: keycloak/replacements-related-keycloak-operator-image.yaml

- path: kafka/replacements-kafka-bootstrap-domain.yaml
- path: kafka/replacements-kafka-broker-0-domain.yaml
- path: kafka/replacements-kafka-broker-1-domain.yaml
- path: kafka/replacements-kafka-broker-2-domain.yaml

- path: kafka/replacements-related-kafka-image.yaml
- path: kafka/replacements-related-kafka-tls-sidecar-image.yaml
- path: kafka/replacements-related-kafka-topic-operator-image.yaml
- path: kafka/replacements-related-kafka-user-operator-image.yaml
- path: kafka/replacements-related-strimzi-operator-image.yaml
- path: kafka/replacements-related-zookeeper-image.yaml



