varReference:
- path: spec/kafka/listeners[]/configuration/bootstrap/host
  kind: Kafka
- path: spec/kafka/listeners[]/configuration/brokers[]/host
  kind: Kafka
- path: spec/template/spec/volumes/secret/secretName
  kind: Deployment