apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: cno-notification
  name: cno-notification
spec:
  ingressClassName: nginx
  rules:
  tls:
  - hosts:
      - cno-notification.cno-dev.gocno.io
    secretName: cno-test-com-tls
  - host: cno-notification.cluster.beopenit.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: cno-notification
            port:
              number: 3000
