global:
  brockerUrl:

cnoAgent:
  image: docker.io/beopenit/cno-agent:1.0.0-rc

cnoOnboardingOperator:
    image: docker.io/beopenit/onboarding-operator-kubernetes:1.0.0-rc

cnocdOperator:
    image: docker.io/beopenit/cno-cd-operator:1.0.0-rc