apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
    component: database
  name: keycloak-postgresql
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keycloak
      component: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
        component: database
      name: keycloak-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USERNAME
              name: keycloak-db-secret
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: keycloak-db-secret
        - name: POSTGRESQL_DATABASE
          value: root
        image: {{ .Values.keycloak.databaseImage | default "registry.access.redhat.com/rhscl/postgresql-10-rhel7:1" }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: keycloak-postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
              'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: keycloak-postgresql-claim
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: keycloak-postgresql-claim
        persistentVolumeClaim:
          claimName: keycloak-postgresql-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: keycloak
  name: keycloak-postgresql-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keycloak.dbstorage | default "15Gi" }}
  volumeMode: Filesystem


---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: keycloak
    component: database
  sessionAffinity: None
  type: ClusterIP
