apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrolebinding.yaml
  - crd.yaml
  - configmap.yaml
  - deployment.yaml
  - keycloak-postgresql.yaml
  - keycloak.yaml
