apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: cno-realm
  labels:
    app: sso
spec:
  realm:
    id: "cno"
    realm: "cno"
    enabled: True
    displayName: "CNO REALM"
  registrationAllowed: true
  users:
  - username: "realm_admin"
    firstName: "John"
    lastName: "Doe"
    email: "jdoe@redhat.com"
    enabled: True
    emailVerified: False
    realmRoles:
    - "offline_access"
    - "uma_authorization"
    clientRoles:
      account:
      - "manage-account"
      - "view-profile"
      realm-management:
      - "manage-users"
      - "view-users"
      - "query-users"
      - "create-client"
  clients:
  - adminUrl: "cno-auth.beopenit.com"
    baseUrl: "cno-auth.beopenit.com"
    bearerOnly: false
    clientAuthenticatorType: "public"
    clientId: "public"
    consentRequired: false
    defaultRoles:
      - "manage-users"
      - "manage-realm"
    directAccessGrantsEnabled: false
    enabled: true
    frontchannelLogout:
      description: True if this client supports Front Channel logout.
      type: boolean
    fullScopeAllowed: true
    implicitFlowEnabled: true
    protocol: "openid-connect"
    publicClient: true
    redirectUris:
    - "*"
    webOrigins:
    - "*"
    rootUrl: "https://cno-auth.beopenit.com/"
    secret: "my-secret"
    serviceAccountsEnabled: true
    standardFlowEnabled: true
  instanceSelector:
    matchLabels:
      app: sso
