{{- if not (lookup "v1" "secret" .Release.Namespace "cno-config") -}}
apiVersion: v1
kind: Secret
metadata:
  name: cno-config
type: Opaque
data:
  username: YWRtaW4=
  cnoSuperAdminPassword: {{ .Values.cnoSuperAdminPassword }}
  oidc_client_secret: {{ randAlphaNum 20 | b64enc }}
{{- end -}}