---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cno-cd-operator
  namespace: {{ .Release.Namespace }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cno-cd-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cno-cd-operator
  template:
    metadata:
      labels:
        app: cno-cd-operator
    spec:
      serviceAccountName: cno-cd-operator
      containers:
        - name: cno-cd-operator
          image: {{ .Values.cnoCD.image.name }}:{{ .Values.cnoCD.image.version }}
          imagePullPolicy: Always
          resources:
          {{- if hasKey .Values.cnoCD "resources" }}
          {{- toYaml .Values.cnoCD.resources | nindent 12 }}
          {{- end }}
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cno-cd-operator"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cno-cd-operator
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - cnocd.beopenit.com
    resources:
      - workloads
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cnocd.beopenit.com
    resources:
      - workloads/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cno-cd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cno-cd-operator
subjects:
  - kind: ServiceAccount
    name: cno-cd-operator
    namespace: {{ .Release.Namespace }}

---

# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cno-cd-operator-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cno-cd-operator-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cno-cd-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: cno-cd-operator
    namespace: {{ .Release.Namespace }}
