apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBzCCAe+gAwIBAgIUfnDPs3hRXg0AJpS8GIDgLnE0NGowDQYJKoZIhvcNAQEL
    BQAwEzERMA8GA1UEAwwIa2V5Y2xvYWswHhcNMjIwMzE4MTE1NDUwWhcNNDkwODAz
    MTE1NDUwWjATMREwDwYDVQQDDAhrZXljbG9hazCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBALcfeHRHvjQ5jqU1zruLX/cfcF+1CR32rEl7N+UMHzmBhsCY
    eNGrxBZrwlq3f7C43jq6Ee4n2ufHn1ld/deI1bNtgqvht6yWZZa8RTH7gVv1DVF6
    3XDeYjh5pFUAJifvUttqwQWvKgNvvfWSnIsHTHiPhjmktCl1r24febNixXo2Aagu
    wXLaj2rMTkoLTchq0FZbKrNLqaEMTJhH/1DZ/G3Aa4lzLK4F/ICod56TGko34fvq
    apOx+KNcJ8hmibQXY9giayo+1zs7pi2vKasMujEQ0lRxAgPfa1FLwT6+fw8x0+8K
    BkxD82DPK8ocFFWL3kqImDZs61R6EhMmnOaQPjUCAwEAAaNTMFEwHQYDVR0OBBYE
    FD49aSa8CcQGRCo1wDtJ1Fo2r6M8MB8GA1UdIwQYMBaAFD49aSa8CcQGRCo1wDtJ
    1Fo2r6M8MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBACHVMBx1
    rVtjkfaKeomvAC0E4ov9rWLQuA6KOrDT/bLQ+nCJjo+Dag2bx0zRaS7UloDNu3uL
    ZW0SJqlw7vucaLS5W/o8cZ9VTPPzHd4yJmIhXd5fzAmwYrDq9i9WEf/Jd0zelWld
    21XIy1qhNCVe1pT2rUUiDf58VyHPetNJ4jW2zss1uyi0AURfLd1HHcxTmkpG6MQY
    Qn9HjRWLn5GzcrJsI2gxDw5mn0NcyUBYpdQ/6mQZvJHkK5JEwIRR7vhy7C1+E/nj
    gnDDjlPScJTx8gsFZZcG6HHAf2Z/IiT6N2+V9v2f7mM0nk1v8w4LEd1Bvm9aQsR8
    LYAKuPMvwL3uatU=
    -----END CERTIFICATE-----
  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEITCCAwmgAwIBAgIUDOV7dbXibQaYRAM1S6PTWZGMbAIwDQYJKoZIhvcNAQEL
    BQAwEzERMA8GA1UEAwwIa2V5Y2xvYWswHhcNMjIwMzE4MTE1OTEzWhcNNDkwODAz
    MTE1OTEzWjBlMQswCQYDVQQGEwJDSTEQMA4GA1UECAwHQUJJREpBTjEQMA4GA1UE
    BwwHTUFSQ09SWTERMA8GA1UECgwIQkVPUEVOSVQxDDAKBgNVBAsMA0NOTzERMA8G
    A1UEAwwIa2V5Y2xvYWswggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZ
    KeuTuJXMntm42ROQW4xdELRLNyzWb/Uf+7qFCbj8TkqhSryVeHRW34QFSLYcgVnW
    LtDDqGjFz9GcqRGLvghW8hjUXq8vuh6UL0dO+/oILM1Bl5295Ya2BWnniR6Iaozo
    PG8N9cQO7JqTjrXDuQ2fdhYmVrpQMHFb+p95AiUyPYg0SYwujRd6POAe15onP1bv
    ZxUUMDx77PkwcXww/PrrZBX2eLtSCWZW56So47l3vgMfJWCHN21QbhnRi9YV8x4S
    6jfMWkUzJUz+MDSUnpopOeFoDTdOrDJmyBDRqTrMzORMFs63O10/NlLJ/Z0HZ7pn
    hkqwAJZzJPHqdnR3127tAgMBAAGjggEZMIIBFTBOBgNVHSMERzBFgBQ+PWkmvAnE
    BkQqNcA7SdRaNq+jPKEXpBUwEzERMA8GA1UEAwwIa2V5Y2xvYWuCFH5wz7N4UV4N
    ACaUvBiA4C5xNDRqMAkGA1UdEwQCMAAwCwYDVR0PBAQDAgQwMB0GA1UdJQQWMBQG
    CCsGAQUFBwMBBggrBgEFBQcDAjCBiwYDVR0RBIGDMIGAgghrZXljbG9ha4ITa2V5
    Y2xvYWsuY25vLXN5c3RlbYIXa2V5Y2xvYWsuY25vLXN5c3RlbS5zdmOCH2tleWNs
    b2FrLmNuby1zeXN0ZW0uc3ZjLmNsdXN0ZXKCJWtleWNsb2FrLmNuby1zeXN0ZW0u
    c3ZjLmNsdXN0ZXIubG9jYWwwDQYJKoZIhvcNAQELBQADggEBACWFQn2d9c0x5EU0
    jp8zzuIA0Jvt38UZNZ5ZI+Cb2OJqxlo3gr+CaSUz0eNEW2eOYHJek4nQMFDrn5rn
    0Zv2BzjJk9WFsMc6DZZ4gWCqJ1Rbs5aQK87M8HNMKpcWgJVEo+zxrX7zEoUgNSzj
    8g7s8t1UklCG272uXicDQfwoK3paudZ2CigeQGVzTtSp/Sr/wD5y1apQETxqVPbj
    uJgzfjhEi/6T0j3nFTFBZGy8uMLwJT0lxznwFuEvofsSDIoY/WOthM/Awid3Ybr8
    0igAPjL5QFCuFh14DE3lqzOElr2MBlN0NSnC6SKvizCReM/Psxpu62brWAmDW9mU
    q+ZVGmU=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: 2022-03-18T12:47:51Z
  name: keycloak-certificate
  namespace: $NAMESPACE
