apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  namespace: cno-system
spec:
  containers:
  - image: beopenit/onboarding-api:latest
    imagePullPolicy: Always
    name: api
  imagePullSecrets:
    - name: regcred
