apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cno-kafka-cluster
spec:

  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: {{ .Values.expose.type }}
        tls: true
        authentication:
          type: tls
        {{- if or (eq .Values.expose.type "ingress") (eq .Values.expose.type "route") }}
        configuration:
          bootstrap:
            host: bootstrap-cno.{{ .Values.expose.domain }}
          brokers:
          - broker: 0
            host: broker-0-cno.{{ .Values.expose.domain }}
          - broker: 1
            host: broker-1-cno.{{ .Values.expose.domain }}
          - broker: 2
            host: broker-2-cno.{{ .Values.expose.domain }}
        {{- end }}
    authorization:
      type: simple
      superUsers:
        - CN=cno-kafka-superadmin
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.5"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
    tlsSidecar: {}