apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
  name: cno-pres-install-job-dataplane-config-gen
spec:
  template:
    spec:
      containers:
      - name: kubectl
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        - name: DEFAULT_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: cno-config
              key: default_cluster_id
        image: bitnami/kubectl
        command: ['/bin/sh', '-c', '{{ $.Files.Get "scripts/agent-config-secret-gen.sh" }}' ]
      restartPolicy: Never
      serviceAccountName: cno-api
  backoffLimit: 1