apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cno-ui
  name: cno-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cno-ui
  template:
    metadata:
      labels:
        app: cno-ui
    spec:
      containers:
      - image: beopenit/cno-ui:latest
        name: cno-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: cno-config
              key: CNO_API_DOMAIN
        - name: NOTIFICATION_URL
          valueFrom:
            configMapKeyRef:
              name: cno-config
              key: CNO_NOTIFICATION_DOMAIN