apiVersion: v1
kind: ServiceAccount
metadata:
  name: cno-api
imagePullSecrets:
- name: $SA

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cno-api
subjects:
- kind: ServiceAccount
  name: cno-api
  namespace: $NAMESPACE
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io