---
apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: cno-api-mysql
spec:
  instances: 1
  secretName: cno-api-db-secret
  podSpec:  
  router:
    instances: 1
    podSpec: 
  datadirVolumeClaimTemplate:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: cno-api-mysql-master-external
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: sidecar-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/managed-by: mysql.oracle.com
    app.kubernetes.io/name: mysql
    mysql.oracle.com/cluster: cno-api-mysql
    role: master
  sessionAffinity: None
  type: ClusterIP
