apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: cno-api
spec:
  replicas: 1
  secretName: cno-api-db-secret
  volumeSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: cno-api-db-secret
type: Opaque
data:
  # root password is required to be specified
  ROOT_PASSWORD: TXlzcWxAQ24wQDJPMjJACg==
  USER: cm9vdAo=
  DATABASE: Y25vYXBpCg==
  PASSWORD: Q04wLWFwaV9NeXNxTHBAc3N3b3JkCg==
---
apiVersion: v1
kind: Service
metadata:
  name: cno-api-mysql-master-external
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: sidecar-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/managed-by: mysql.presslabs.org
    app.kubernetes.io/name: mysql
    mysql.presslabs.org/cluster: cno-api
    role: master
  sessionAffinity: None
  type: ClusterIP