apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cno-kafka-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            host: bootstrap-cno.INGRESS_DOMAIN
          brokers:
          - broker: 0
            host: broker-0-cno.INGRESS_DOMAIN
          - broker: 1
            host: broker-1-cno.INGRESS_DOMAIN
          - broker: 2
            host: broker-2-cno.INGRESS_DOMAIN
    authorization:
      type: simple
      superUsers:
        - CN=cno-kafka-superadmin
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
