apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: onboarding
  namespace: cno
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls: []
