apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
  labels:
    app: sso
data: # all values Base64
  POSTGRES_DATABASE:  $POSTGRES_DBNAME
  POSTGRES_EXTERNAL_ADDRESS: $POSTGRES_IP
  POSTGRES_EXTERNAL_PORT: $POSTGRES_PORT
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_USERNAME:  $POSTGRES_USERS
type: Opaque