apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cno-kafka-cluster
spec:
  kafka:
    template:
      pod:
        imagePullSecrets:
        - name: $SA
    image: "strimzi/kafka:0.20.0-kafka-2.5.0"
    version: 2.5.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            host: bootstrap-cno.$(DOMAIN)
          brokers:
          - broker: 0
            host: broker-0-cno.$(DOMAIN)
          - broker: 1
            host: broker-1-cno.$(DOMAIN)
          - broker: 2
            host: broker-2-cno.$(DOMAIN)
    authorization:
      type: simple
      superUsers:
        - CN=cno-kafka-superadmin
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.5"
    storage:
      type: ephemeral
  zookeeper:
    template:
      pod:
        imagePullSecrets:
        - name: $SA
    image: "strimzi/kafka:0.20.0-kafka-2.5.0"
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    template:
      pod:
        imagePullSecrets:
        - name: $SA
    topicOperator:
      image: "strimzi/operator:0.20.0"
    userOperator:
      image: "strimzi/operator:0.20.0"
    tlsSidecar:
      image: "strimzi/kafka:0.20.0-kafka-2.5.0"
