source:
  kind: ConfigMap
  name: cno-config
  fieldPath: data.KAFKA_BROKER_0_DOMAIN
targets:
- select:
    kind: kafka
    name: cno-kafka-cluster
  fieldPaths:
  - spec.kafka.listeners.[name=external].configuration.brokers.[broker=0].host