cat <<EOF | kubectl -n kafka apply -f -
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      external:
        type: loadbalancer
        authentication:
          type: tls
        overrides:
          bootstrap:
            address: bootstrap.kafka.cloud.beopenit.com
          brokers:
          - broker: 0
            advertisedHost: broker-0.kafka.cloud.beopenit.com
          - broker: 1
            advertisedHost: broker-1.kafka.cloud.beopenit.com
          - broker: 2
            advertisedHost: broker-2.kafka.cloud.beopenit.com
      tls:
        authentication:
          type: tls
    authorization:
      type: simple
      superUsers:
        - CN=onboarding
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
EOF
