apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: cno-api
spec:
  secretName: cno-api-db-secret
  image: mysql:8.0.27
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cno-api-mysql-master-external
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: sidecar-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: mysql
    mysql.presslabs.org/cluster: cno-api
    role: master
  sessionAffinity: None
  type: ClusterIP