apiVersion: v1
kind: ServiceAccount
metadata:
  name: cno-api
  namespace: cno-system

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cno-api
subjects:
- kind: ServiceAccount
  name: cno-api
  namespace: cno-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    fluxcd.io/automated: 'true'
  labels:
    run: cno-api
  name: cno-api
  namespace: cno-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: cno-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        run: cno-api
    spec:
      containers:
      - image: beopenit/cno-api:v0.0.0.1..5d1f00c
        imagePullPolicy: Always
        name: cno-api
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: IN_CLUSTER
          value: "true"
        - name: SERVER_URL
          value: $SERVER_URL
        - name: OIDC_SERVER_URL
          value: $OIDC_SERVER_URL
        - name: OIDC_REALM
          value: $OIDC_REALM
        - name: OIDC_SERVER_BASE_URL
          value: $OIDC_SERVER_BASE_URL
        - name: OIDC_CLIENT_ID
          value: "cno-api"
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-client-cno-api
              key: OIDC_CLIENT_SECRET
        - name: KAFKA_BROKERS
          value: $KAFKA_BROKERS
        - name: KAFKA_TlS_ENABLED
          value: "true"
        - name: KAFKA_TLS_SKIP_VERIFY
          value: "false"
        - name: KAFKA_VERBOSE
          value: "false"
        - name: DB_HOST
          value: "cno-api-mysql-master"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "cnoapi"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cno-api-db-secret
              key: ROOT_PASSWORD
        - name: CREATE_DEFAULT_CLUSTER
          value: $CREATE_DEFAULT_CLUSTER
        - name: DEFAULT_CLUSTER_ID
          value: $DEFAULT_CLUSTER_ID
        volumeMounts:
        - name: kafkaconfig
          mountPath: "/root/.key"
          readOnly: true
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: cno-api
      volumes:
      - name: kafkaconfig
        secret:
          secretName: kafkaconfig

---
apiVersion: v1
kind: Service
metadata:
  name: cno-api
  namespace: cno-system
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  selector:
    run: cno-api
  sessionAffinity: None
  type: LoadBalancer