source:
  kind: ConfigMap
  name: cno-config
  fieldPath: data.MYSQL_OPERATOR_IMAGE
targets:
- select:
    kind: StatefulSet
    name: mysql-operator
  fieldPaths:
  - spec.template.spec.containers.[name=operator].image