kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onboarding-operator-kubernetes
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
subjects:
  - kind: ServiceAccount
    name: onboarding-operator-kubernetes
    namespace: onboarding
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
