apiVersion: onboarding.beopenit.com/v1alpha1
kind: Environment
metadata:
  name: example-environment
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
spec:
  name: projet1
  resources:
    requests:
      cpu: 1000m
      memory: 100Mi
      ephemeral-storage: 1Gi
    limits:
      cpu: 2000m
      memory: 500Mi
      ephemeral-storage: 2Gi
  storage: 10Gi
  users:
  - email: findme@gmail.com
    environmentId: "123456"
    id: "987654"
    role: owner
    userFullName: "Hello world"
    username: lima
