apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: cno-realm
  labels:
    app: sso
spec:
  realm:
    id: "cno"
    realm: "cno"
    enabled: True
    displayName: "CNO REALM"
  registrationAllowed: true
  instanceSelector:
    matchLabels:
      app: sso
