apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy: {}
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:16.1.0
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        restartPolicy: Always            
        env:
        - name: DB_ADDR
          value: cno-api-mysql
        - name: DB_DATABASE
          value: cno
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cno-api-db-secret
              key: ROOT_PASSWORD
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_VENDOR
          value: mysql
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ADMIN_PASSWORD
              name: credential-keycloak
        - name: KEYCLOAK_USER
          secretKeyRef:
            key: keycloak-username
            name: credential-keycloak
      
---