apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: cloud-keycloak
  labels:
    app: sso
spec:
  instances: 1
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: True
  podDisruptionBudget:
    enabled: True
  # User needs to provision the external database
  externalDatabase:
    enabled: True
  keycloakDeploymentSpec:
    podlabel: sso
    experimental:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sso
              topologyKey: "topology.kubernetes.io/zone"
          - weight: 90
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sso
              topologyKey: "kubernetes.io/hostname"
