apiVersion: v1
kind: Service
metadata:
  labels:
    app: cno-ui
  name: cno-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cno-ui
  {{ if or (eq .Values.expose.type "ingress") (eq .Values.expose.type "route") }}
  type: ClusterIP
  {{ else if eq .Values.expose.type "nodeport"  }}
  type: NodePort
  {{ else if eq .Values.expose.type "loadbalancer"  }}
  type: LoadBalancer
  {{ end }}