---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cno-ui
  name: cno-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cno-ui
  template:
    metadata:
      labels:
        app: cno-ui
    spec:
      containers:
        - image: mordioum/cno-ui
          name: cno-ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}
          env:
            - name: API_URL
              value: http://20.67.180.91
            - name: NOTIFICATION_URL
              value: http://20.67.213.205
            - name: OIDC_CLIENT_ID
              value: "public"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cno-ui
  name: cno-ui
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: cno-ui
  type: LoadBalancer
