kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onboarding-operator-kubernetes
subjects:
  - kind: ServiceAccount
    name: onboarding-operator-kubernetes
    namespace: cno-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
