apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak-operator
  template:
    metadata:
      labels:
        name: keycloak-operator
    spec:
      serviceAccountName: keycloak-operator
      containers:
      - name: keycloak-operator
        # Replace this with the built image name
        image: {{ .Values.operatorImage | default "quay.io/keycloak/keycloak-operator:15.0.1" }}
        command:
        - keycloak-operator
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "keycloak-operator"
        - name: RELATED_IMAGE_KEYCLOAK
          value: {{ .Values.image | default "quay.io/keycloak/keycloak:12.0.1" }}
        - name: RELATED_IMAGE_POSTGRESQL
          value: {{ .Values.databaseImage | default "registry.access.redhat.com/rhscl/postgresql-10-rhel7:1" }}
        - name: RELATED_IMAGE_KEYCLOAK_INIT_CONTAINER
          value: {{ .Values.initContainerImage | default "quay.io/keycloak/keycloak-init-container:master" }}