apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: cloud-keycloak
  labels:
    app: sso
spec:
  instances: 1
  externalDatabase:
    enabled: true
  externalAccess:
    enabled: false
    tlsTermination: passthrough
  podDisruptionBudget:
    enabled: True
  keycloakDeploymentSpec:
    experimental:
      volumes:
        items:
        - name: cno-realm
          mountPath: /cno
          configMaps:
          - cno-realm
      env:
      - name: KEYCLOAK_IMPORT
        value: /cno/cno-realm.json
