{{- $rootPasswordValue := (randAlpha 16) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "keycloak-db-secret") }}
{{- if $secret }}
{{- $rootPasswordValue = index $secret.data "POSTGRES_PASSWORD" }}
{{- end -}}
apiVersion: v1
data:
  POSTGRES_EXTERNAL_ADDRESS: {{ printf "%s.%s.%s" "keycloak-db" .Release.Namespace "svc.cluster.local" | b64enc }}
  POSTGRES_EXTERNAL_PORT: NTQzMgo=
  POSTGRES_SUPERUSER: dHJ1ZQo=
  POSTGRES_DATABASE: cm9vdA==
  POSTGRES_HOST: {{ printf "%s.%s.%s" "keycloak-postgresql" .Release.Namespace "svc.cluster.local" | b64enc }}
  POSTGRES_PASSWORD: {{ $rootPasswordValue }}
  POSTGRES_USERNAME: a2V5Y2xvYWs=
  POSTGRES_VERSION: MTA=
kind: Secret
metadata:
  labels:
    app: keycloak
  name: keycloak-db-secret
type: Opaque