apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: cloud-keycloak
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
  namespace: keycloak
  labels:
    app: sso
spec:
  instances: 3
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: false
  podDisruptionBudget:
    enabled: True
